version: '3.6'

services:
  application:
    user: "${UID:-1000}:${GID:-1000}" #don't run as root by default to prevent permission conflicts
    build:
      context: docker/application
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/app
      - $HOME/.phive:/home/application/.phive
      - $HOME/.ssh:/home/application/.ssh
      - $HOME/.gitconfig:/home/application/.gitconfig
      - ${SSH_AUTH_SOCK:-/ssh-agent}:/ssh-agent # Forward local machine SSH key to docker
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - docker/application/environment.yml
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
  integrationtests.webserver:
    image: nginx:alpine
    volumes:
      - ./docker/integrationtests:/usr/share/nginx/html:ro
    ports:
      - "${INTEGRATION_TESTS_LOCAL_PORT_HTTP:-}:80"
      - "${INTEGRATION_TESTS_LOCAL_PORT_HTTPS:-}:443"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost/test.html" ]
      interval: 1s
      timeout: 10s
      start_period: 10s
      retries: 10
