
name: CI

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '**.md'

jobs:
  ci:
    uses: codenamephp/workflows.php/.github/workflows/ci.yml@1
    with:
      php-versions: '["8.2"]'
      test-command: |
        INTEGRATION_TESTS_LOCAL_PORT_HTTP=80 \
        INTEGRATION_TESTS_LOCAL_PORT_HTTPS=443 \
        docker-compose up -d --wait --build --force-recreate --remove-orphans integrationtests.webserver && \
        INTEGRATION_TESTS_HOST=localhost composer ci-all
